Vagrant.configure("2") do |config|
	config.hostmanager.enabled = true
	config.hostmanager.manage_host = true

#Vm for ansible configuration management and terraform for provisioning of infrastructure
	config.vm.define "terrans" do |terrans|
		terrans.vm.box = "ubuntu/xenial64"
		terrans.vm.hostname = "terrans"
		terrans.vm.network "private_network", ip: "192.168.56.30"
	#provision is used to perform additional action after the creation of the vm, like running a shell script
		terrans.vm.provision "shell", path: "terrans.sh"
	#below block is use to add additional specifications to the vm like: cpu, memory, disk space, gui...
		terrans.vm.provider "virtualbox" do |add|
			add.memory = "2064"
		#storage size specification 
			add.disksize.size = "50GB"
		end 
	end
end




